### ISSUE TITLE
Missing step to create manifest.json in the tutorial

### ISSUE THREAD

**Issue by jhuiting** [Actyx/chat-tutorial#5]
While executing the tutorial I've noticed that the step to create `manifest.json` seems to be missing in the tutorial. Thanks for the full code, I've downloaded the manifest from this repo.

**Comment by o1iver** [comment]
Indeed, @jhuiting! Thanks for reporting this. We will fix it asap.

**Comment by jhuiting** [comment]
Fastest reply I've ever received GH @o1iver (within 30s) 🏆 Thanks for fixing.

**Comment by o1iver** [comment]
This has been fixed now (see https://developer.actyx.com/docs/tutorials/chat#the-user-interface). Thanks again for bringing it up @jhuiting!

Hope you are enjoying Actyx. If you have any questions, don't hesitate to get on our [Discord](https://discord.gg/262yJhc) or post in the [Community Forum](https://community.actyx.com/).
